import Team from '../models/Team.js';

const defaultTeam = [
  {
    name: 'Ayesha Khan',
    position: 'Full Stack Developer',
    label: 'Engineering',
    shortBio: 'Builds reliable product experiences from interface to API.',
    about: 'Ayesha turns complex product requirements into clear, dependable digital experiences across frontend architecture and backend services.',
    location: 'Lahore, Pakistan',
    email: 'ayesha@azmeer.com',
    phone: '+92 3328657885',
    experience: '6+ years',
    availability: 'Available for product engineering projects',
    skills: ['React', 'Node.js', 'MongoDB', 'REST APIs', 'System Design'],
    focus: ['Product architecture', 'API design', 'Performance'],
    portfolio: ['AZ MEER Business Suite', 'Field Connect', 'Rapid Commerce'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1000&q=85',
    socialLinks: { linkedin: '#', github: '#', twitter: '#' },
  },
  {
    name: 'Musa Ali',
    position: 'Frontend Developer',
    label: 'Engineering',
    shortBio: 'Creates fast, expressive interfaces that stay accessible and maintainable.',
    about: 'Musa specializes in turning product direction into polished interfaces with responsive interaction and practical component systems.',
    location: 'Islamabad, Pakistan',
    email: 'musa@azmeer.com',
    phone: '+92 3328657885',
    experience: '5+ years',
    availability: 'Available for frontend and design-system work',
    skills: ['React', 'JavaScript', 'Tailwind CSS', 'Framer Motion', 'Accessibility'],
    focus: ['Interaction design', 'Design systems', 'Responsive UI'],
    portfolio: ['Mezzy Mobile App', 'Luma Retail Journey', 'AZ MEER Web Platform'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=85',
    socialLinks: { linkedin: '#', github: '#', twitter: '#' },
  },
  {
    name: 'Sara Malik',
    position: 'Backend Developer',
    label: 'Engineering',
    shortBio: 'Designs secure services and data flows for dependable products.',
    about: 'Sara works across APIs, data models, authentication, and service reliability with a security-minded approach.',
    location: 'Lahore, Pakistan',
    email: 'sara@azmeer.com',
    phone: '+92 3328657885',
    experience: '5+ years',
    availability: 'Available for backend and platform projects',
    skills: ['Node.js', 'Express', 'MongoDB', 'JWT', 'Security'],
    focus: ['API architecture', 'Data modeling', 'Authentication'],
    portfolio: ['Operations Dashboard', 'Secure Client Portal', 'Field Connect API'],
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1000&q=85',
    socialLinks: { linkedin: '#', github: '#', twitter: '#' },
  },
  {
    name: 'Zain Ahmed',
    position: 'UI/UX Designer',
    label: 'Design',
    shortBio: 'Shapes clear product journeys through research and thoughtful visual direction.',
    about: 'Zain connects user research, content hierarchy, visual design, and prototyping to create interfaces with a clear purpose.',
    location: 'Karachi, Pakistan',
    email: 'zain@azmeer.com',
    phone: '+92 3328657885',
    experience: '7+ years',
    availability: 'Available for discovery and product design engagements',
    skills: ['Figma', 'UX Research', 'Prototyping', 'Design Systems', 'Product Strategy'],
    focus: ['User journeys', 'Wireframes', 'Visual systems'],
    portfolio: ['NextWave Health', 'Mezzy Mobile App', 'Luma Retail Journey'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1000&q=85',
    socialLinks: { linkedin: '#', github: '#', twitter: '#' },
  },
  {
    name: 'Nadia Hassan',
    position: 'Project Manager',
    label: 'Delivery',
    shortBio: 'Keeps ambitious digital work focused, transparent, and moving toward launch.',
    about: 'Nadia connects client goals with delivery, making scope visible and helping multidisciplinary teams turn uncertainty into an actionable plan.',
    location: 'Lahore, Pakistan',
    email: 'nadia@azmeer.com',
    phone: '+92 3328657885',
    experience: '8+ years',
    availability: 'Available for product planning and delivery leadership',
    skills: ['Roadmaps', 'Agile Delivery', 'Client Success', 'Planning', 'Quality Assurance'],
    focus: ['Discovery workshops', 'Delivery planning', 'Stakeholder alignment'],
    portfolio: ['UrbanOps', 'AZ MEER Business Suite', 'NextWave Health'],
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1000&q=85',
    socialLinks: { linkedin: '#', github: '#', twitter: '#' },
  },
];

export const seedTeam = async () => {
  const teamCount = await Team.countDocuments();
  if (teamCount > 0) return;

  await Team.insertMany(defaultTeam);
  console.log(`Team seed created ${defaultTeam.length} members`);
};
